import os

# download dataset
RAW_DIR = "../data/raw"
RAW_FILENAME = 'input.csv'
RAW_PATH = os.path.join(RAW_DIR, RAW_FILENAME)

# data preparation
PREPARED_DIR = "../target/prepared"

## use by pandas
LABEL_ENCODING_FILENAME = "label_encoder_species.pkl"
LABEL_ENCODING_PATH = os.path.join(PREPARED_DIR, LABEL_ENCODING_FILENAME)
PREPARED_DATA_FILENAME = "prepared_data.csv"
PREPARED_DATA_PATH = os.path.join(PREPARED_DIR, PREPARED_DATA_FILENAME)
PREPARED_DATA_PARQUET_FILENAME = "prepared_data.parquet"
PREPARED_DATA_PARQUET_PATH = os.path.join(PREPARED_DIR, PREPARED_DATA_PARQUET_FILENAME)

## use by apache spark
SPECIES_INDEXER_MODEL_FILENAME="species_indexer_model"
SPECIES_INDEXER_MODEL_PATH = os.path.join(PREPARED_DIR, SPECIES_INDEXER_MODEL_FILENAME)
PREPARED_DATA_SPARK_FILENAME = "prepared_data.csv_spark"
PREPARED_DATA_SPARK_PATH = os.path.join(PREPARED_DIR, PREPARED_DATA_SPARK_FILENAME)
PREPARED_DATA_PARQUET_SPARK_FILENAME = "prepared_data.parquet_spark"
PREPARED_DATA_PARQUET_SPARK_PATH = os.path.join(PREPARED_DIR, PREPARED_DATA_PARQUET_SPARK_FILENAME)

# sklearn training
INPUT_PATH=PREPARED_DATA_PARQUET_PATH
FEATURE_COLS = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
MODELS_DIR = "../target/models"

SCALER_JOBLIB_FILENAME="scaler_sklearn.joblib"
MODEL_JOBLIB_FILENAME="model_sklearn.joblib"
MODEL_PICKLE_FILENAME="model_sklearn.pkl"

SCALER_JOBLIB_PATH = os.path.join(MODELS_DIR, SCALER_JOBLIB_FILENAME)
MODEL_JOBLIB_PATH = os.path.join(MODELS_DIR, MODEL_JOBLIB_FILENAME)
MODEL_PICKLE_PATH = os.path.join(MODELS_DIR, MODEL_PICKLE_FILENAME)

